---
name: Deploy

on:
  push:
    branches:
      - main
  # Scheduled tasks only run on the main branch.
  #schedule:
  #  - cron: '0 10 * * *'  # Daily at 10AM UTC.
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Clone code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Fetch latest packages data and build the website
        run: |
          make generate

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git add .
          git commit -m "Update website"
          git push

